# Generated by Django 5.2.5 on 2025-08-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=16, unique=True)),
                ('label', models.CharField(blank=True, max_length=64)),
                ('status_color', models.CharField(choices=[('black', 'Negro'), ('red', 'Rojo'), ('blue', 'Azul'), ('green', 'Verde')], default='green', max_length=8)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
